image: soxueren/docker-maven:latest

variables:
  REGISTRY_URL: "soxueren"
  IMAGE_TAG: "1.11"

services:
  - docker:dind

stages:
  - build

build-image:
  stage: build
  before_script:
    - docker login -u soxueren -p 1995jxw
  script:
    - docker build --pull -t $REGISTRY_URL/mapproxy:$IMAGE_TAG .
    - docker push $REGISTRY_URL/mapproxy:$IMAGE_TAG
